AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TwilioLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TwilioLambda   # Nome explícito da função Lambda
      Handler: index.handler      # Referência para a função exportada no index.js
      Runtime: nodejs20.x         # Versão do Node.js que sua Lambda usa
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail         # Permissão para enviar e-mail
              - ses:SendRawEmail      # Permissão para enviar e-mails brutos
            Resource: "*"

Parameters:
  TwilioAccountSid:
    Type: String
    NoEcho: true
  TwilioAuthToken:
    Type: String
    NoEcho: true
